In [ ]:
import pandas  as pd
import numpy as np
import seaborn as  sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/healthcare_raw.csv")

In [29]:
df.head()
df.isnull().sum()

Patient_ID           0
Gender               0
Age                  0
Medical_Condition    0
Admission_Date       0
Admission_Type       0
Medical_Code         0
Billing_Amount       0
Discharge_Date       0
dtype: int64

In [30]:
df

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,2026-01-15,urgent,ICD10 I10,4500.0,2026-01-20
1,P1002,Female,32,Pneumonia,2026-01-16,emergency,ICD10 J18,6700.5,2026-01-22
2,P1003,Male,68,Diabetes Type 2,2026-01-16,routine,ICD10 E11,3200.0,2026-01-18
3,P1004,Female,55,Asthma,2026-01-17,emergency,ICD10 J45,5800.0,2026-01-19
4,P1005,Male,29,Fracture,2026-01-17,urgent,ICD10 S52,8500.0,2026-01-25
...,...,...,...,...,...,...,...,...,...
495,P1496,Female,50,COPD,2026-09-20,emergency,ICD10 J44,9800.0,2026-09-23
496,P1497,Male,28,Fracture,2026-09-20,urgent,ICD10 S52,9400.0,2026-09-24
497,P1498,Female,67,Heart Attack,2026-09-21,emergency,ICD10 I21,14200.0,2026-09-25
498,P1499,Male,43,Diabetes Type 2,2026-09-21,routine,ICD10 E11,4900.0,2026-09-23
499,P1500,Female,61,Stroke,2026-09-22,emergency,ICD10 I63,13900.0,2026-09-26

In [31]:
df.duplicated().sum()

np.int64(0)

In [32]:
df.shape

(500, 9)

In [ ]:
df.dtypes

Patient_ID            object
Gender                object
Age                    int64
Medical_Condition     object
Admission_Date        object
Admission_Type        object
Medical_Code          object
Billing_Amount       float64
Discharge_Date        object
dtype: object

In [ ]:
df["Admission_Date"]=pd.to_datetime(df["Admission_Date"])
df["Discharge_Date"]=pd.to_datetime(df["Discharge_Date"])

/tmp/ipykernel_1960/1752859377.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Admission_Date"]=pd.to_datetime(df["Admission_Date"])
/tmp/ipykernel_1960/1752859377.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Discharge_Date"]=pd.to_datetime(df["Discharge_Date"])

In [ ]:
df["Admission_Date"].dtypes
df["Discharge_Date"].dtypes

dtype('<M8[ns]')

In [ ]:
df["Gender"].value_counts()

Gender
Male      250
Female    250
Name: count, dtype: int64

In [ ]:
df["Admission_Type"].value_counts()

Admission_Type
Routine      196
Emergency    188
Urgent       116
Name: count, dtype: int64

In [ ]:
df["Admission_Type" ]=(
    df["Admission_Type"]
    .str.strip()
    .str.lower()
)
df["Admission_Type"]

0         urgent
1      emergency
2        routine
3      emergency
4         urgent
         ...
495    emergency
496       urgent
497    emergency
498      routine
499    emergency
Name: Admission_Type, Length: 500, dtype: object

In [ ]:
df.columns

Index(['Patient_ID', 'Gender', 'Age', 'Medical_Condition', 'Admission_Date',
       'Admission_Type', 'Medical_Code', 'Billing_Amount', 'Discharge_Date'],
      dtype='object')

In [ ]:
df["Medical_Code"].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Medical_Code, Length: 500, dtype: bool

In [ ]:
df["Medical_Code"].isnull().sum()

np.int64(15)

In [ ]:
df["Medical_Code"]=df["Medical_Code"].fillna("unknown")

In [33]:
df["Medical_Code"].isnull().sum()

np.int64(0)

In [35]:
df[["Admission_Date","Discharge_Date"]].dtypes

Admission_Date    datetime64[ns]
Discharge_Date    datetime64[ns]
dtype: object

In [36]:
df['Admission_Type'].value_counts()

Admission_Type
routine      196
emergency    188
urgent       116
Name: count, dtype: int64

In [37]:
df["Hos_stay_days"]=(df["Discharge_Date"]-df['Admission_Date']).dt.days
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date,Hos_stay_days
0,P1001,Male,45,Hypertension,2026-01-15,urgent,ICD10 I10,4500.0,2026-01-20,5
1,P1002,Female,32,Pneumonia,2026-01-16,emergency,ICD10 J18,6700.5,2026-01-22,6
2,P1003,Male,68,Diabetes Type 2,2026-01-16,routine,ICD10 E11,3200.0,2026-01-18,2
3,P1004,Female,55,Asthma,2026-01-17,emergency,ICD10 J45,5800.0,2026-01-19,2
4,P1005,Male,29,Fracture,2026-01-17,urgent,ICD10 S52,8500.0,2026-01-25,8

In [43]:
df[['Admission_Date','Medical_Code','Discharge_Date','Admission_Type','Hos_stay_days']].head()

  Admission_Date Medical_Code Discharge_Date Admission_Type  Hos_stay_days
0     2026-01-15    ICD10 I10     2026-01-20         urgent              5
1     2026-01-16    ICD10 J18     2026-01-22      emergency              6
2     2026-01-16    ICD10 E11     2026-01-18        routine              2
3     2026-01-17    ICD10 J45     2026-01-19      emergency              2
4     2026-01-17    ICD10 S52     2026-01-25         urgent              8

In [44]:
df['Billing_Amount'].describe()

count      500.00000
mean      7249.00100
std       3198.96932
min       2300.00000
25%       4400.00000
50%       6950.00000
75%       9400.00000
max      14200.00000
Name: Billing_Amount, dtype: float64

In [45]:
df['Medical_Condition'].value_counts()

Medical_Condition
COPD                       34
Appendicitis               33
Stroke                     33
Pneumonia                  31
Heart Failure              30
Kidney Stone               28
Hypertension               28
Heart Attack               27
Fracture                   22
Gastritis                  21
Skin Infection             20
Back Pain                  20
Asthma                     19
Parkinson's Disease        19
Urinary Tract Infection    18
Pregnancy                  16
Diabetes Type 2            16
Allergic Reaction          15
Gallstones                 15
Diabetes Type 1            15
Osteoporosis               12
Osteoarthritis             12
Anxiety Disorder            9
Migraine                    6
Hypothyroidism              1
Name: count, dtype: int64

In [46]:
pd.crosstab(
    df['Admission_Type'],
    df['Medical_Condition']
    )

Medical_Condition,Allergic Reaction,Anxiety Disorder,Appendicitis,Asthma,Back Pain,COPD,Diabetes Type 1,Diabetes Type 2,Fracture,Gallstones,...,Kidney Stone,Migraine,Osteoarthritis,Osteoporosis,Parkinson's Disease,Pneumonia,Pregnancy,Skin Infection,Stroke,Urinary Tract Infection
Admission_Type,,,,,,,,,,,,,,,,,,,,,
emergency,0,0,33,1,0,34,0,0,0,0,...,28,0,0,0,0,31,0,0,33,0
routine,0,9,0,0,0,0,15,16,0,15,...,0,6,12,12,19,0,16,0,0,18
urgent,15,0,0,18,20,0,0,0,22,0,...,0,0,0,0,0,0,0,20,0,0

In [47]:
df.groupby('Medical_Condition')['Age'].mean()

Medical_Condition
Allergic Reaction          33.400000
Anxiety Disorder           37.111111
Appendicitis               33.090909
Asthma                     41.894737
Back Pain                  40.650000
COPD                       65.176471
Diabetes Type 1            50.200000
Diabetes Type 2            52.375000
Fracture                   38.909091
Gallstones                 49.066667
Gastritis                  40.047619
Heart Attack               65.925926
Heart Failure              64.433333
Hypertension               53.392857
Hypothyroidism             52.000000
Kidney Stone               49.000000
Migraine                   30.500000
Osteoarthritis             53.166667
Osteoporosis               54.166667
Parkinson's Disease        72.631579
Pneumonia                  57.709677
Pregnancy                  29.187500
Skin Infection             33.150000
Stroke                     63.242424
Urinary Tract Infection    43.777778
Name: Age, dtype: float64